<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SistemaAN.Api</RootNamespace>
    <AssemblyName>SistemaAN.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaAN.Application\SistemaAN.Application.csproj" />
    <ProjectReference Include="..\SistemaAN.Infrastructure\SistemaAN.Infrastructure.csproj" />
  </ItemGroup>

</Project>
