// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaAN.Infrastructure.Persistence;

#nullable disable

namespace SistemaAN.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612120000_AddPets")]
    partial class AddPets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PapelUsuario", b =>
                {
                    b.Property<long>("PapeisId")
                        .HasColumnType("bigint")
                        .HasColumnName("papeis_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("PapeisId", "UsuarioId")
                        .HasName("pk_usuarios_papeis");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuarios_papeis_usuario_id");

                    b.ToTable("usuarios_papeis", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.CategoriaIngrediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias_ingredientes");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_ingredientes_nome");

                    b.ToTable("categorias_ingredientes", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.Ingrediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("CoeficienteConversao")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("coeficiente_conversao");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CustoAtualKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo_atual_kg");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoConversao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo_conversao");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingredientes");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_ingredientes_categoria_id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredientes_nome");

                    b.ToTable("ingredientes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ingredientes_coeficiente", "coeficiente_conversao > 0");

                            t.HasCheckConstraint("ck_ingredientes_custo", "custo_atual_kg >= 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Clientes.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<int?>("DiaCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("dia_cobranca");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("ObservacoesFinanceiras")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_financeiras");

                    b.Property<string>("OrigemVenda")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("origem_venda");

                    b.Property<string>("Rua")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("rua");

                    b.Property<string>("StatusFinanceiro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_financeiro");

                    b.Property<string>("Telefone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorRecorrenteMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_recorrente_mensal");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_clientes_nome");

                    b.ToTable("clientes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_clientes_dia_cobranca", "dia_cobranca IS NULL OR (dia_cobranca BETWEEN 1 AND 31)");

                            t.HasCheckConstraint("ck_clientes_valor", "valor_recorrente_mensal >= 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Consumo.FaixaConsumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GramasPorDia")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_por_dia");

                    b.Property<decimal>("PesoFinal")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_final");

                    b.Property<decimal>("PesoInicial")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_inicial");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_faixas_consumo");

                    b.HasIndex("PesoInicial")
                        .HasDatabaseName("ix_faixas_consumo_peso_inicial");

                    b.ToTable("faixas_consumo", "public", t =>
                        {
                            t.HasCheckConstraint("ck_faixas_consumo_gramas", "gramas_por_dia > 0");

                            t.HasCheckConstraint("ck_faixas_consumo_peso", "peso_inicial < peso_final");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.FrequenciaEntrega", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DiasCiclo")
                        .HasColumnType("integer")
                        .HasColumnName("dias_ciclo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<bool>("Personalizada")
                        .HasColumnType("boolean")
                        .HasColumnName("personalizada");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_frequencias_entrega");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_frequencias_entrega_nome");

                    b.ToTable("frequencias_entrega", "public", t =>
                        {
                            t.HasCheckConstraint("ck_frequencias_entrega_dias", "personalizada = true OR (dias_ciclo IS NOT NULL AND dias_ciclo > 0)");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Papel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_papeis");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_papeis_nome");

                    b.ToTable("papeis", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Pets.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int?>("GramasDiaAjustadas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_dia_ajustadas");

                    b.Property<string>("IdadeAprox")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("idade_aprox");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacoesAlimentares")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_alimentares");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_gerais");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_kg");

                    b.Property<string>("Raca")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("raca");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sexo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pets_cliente_id");

                    b.ToTable("pets", "public", t =>
                        {
                            t.HasCheckConstraint("ck_pets_gramas_ajustadas", "gramas_dia_ajustadas IS NULL OR gramas_dia_ajustadas >= 0");

                            t.HasCheckConstraint("ck_pets_peso", "peso_kg > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.ItemReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Gramas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas");

                    b.Property<long>("IngredienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingrediente_id");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("receita_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_receita");

                    b.HasIndex("IngredienteId")
                        .HasDatabaseName("ix_itens_receita_ingrediente_id");

                    b.HasIndex("ReceitaId")
                        .HasDatabaseName("ix_itens_receita_receita_id");

                    b.ToTable("itens_receita", "public", t =>
                        {
                            t.HasCheckConstraint("ck_itens_receita_gramas", "gramas > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<long?>("PetId")
                        .HasColumnType("bigint")
                        .HasColumnName("pet_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_receitas");

                    b.HasIndex("Tipo", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_receitas_tipo_codigo");

                    b.ToTable("receitas", "public");
                });

            modelBuilder.Entity("PapelUsuario", b =>
                {
                    b.HasOne("SistemaAN.Domain.Identity.Papel", null)
                        .WithMany()
                        .HasForeignKey("PapeisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_papeis_papeis_papeis_id");

                    b.HasOne("SistemaAN.Domain.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_papeis_usuarios_usuario_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.Ingrediente", b =>
                {
                    b.HasOne("SistemaAN.Domain.Catalog.CategoriaIngrediente", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredientes_categorias_ingredientes_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("SistemaAN.Domain.Identity.Usuario", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Pets.Pet", b =>
                {
                    b.HasOne("SistemaAN.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pets_clientes_cliente_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.ItemReceita", b =>
                {
                    b.HasOne("SistemaAN.Domain.Catalog.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_receita_ingredientes_ingrediente_id");

                    b.HasOne("SistemaAN.Domain.Receitas.Receita", null)
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_receita_receitas_receita_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.Receita", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
