// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaAN.Infrastructure.Persistence;

#nullable disable

namespace SistemaAN.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612160000_AddEntregas")]
    partial class AddEntregas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PapelUsuario", b =>
                {
                    b.Property<long>("PapeisId")
                        .HasColumnType("bigint")
                        .HasColumnName("papeis_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("PapeisId", "UsuarioId")
                        .HasName("pk_usuarios_papeis");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuarios_papeis_usuario_id");

                    b.ToTable("usuarios_papeis", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.CategoriaIngrediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias_ingredientes");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_ingredientes_nome");

                    b.ToTable("categorias_ingredientes", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.Ingrediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("CoeficienteConversao")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("coeficiente_conversao");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CustoAtualKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo_atual_kg");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoConversao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo_conversao");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingredientes");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_ingredientes_categoria_id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredientes_nome");

                    b.ToTable("ingredientes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ingredientes_coeficiente", "coeficiente_conversao > 0");

                            t.HasCheckConstraint("ck_ingredientes_custo", "custo_atual_kg >= 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Clientes.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<int?>("DiaCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("dia_cobranca");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<long?>("FrequenciaEntregaId")
                        .HasColumnType("bigint")
                        .HasColumnName("frequencia_entrega_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("ObservacoesFinanceiras")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_financeiras");

                    b.Property<string>("OrigemVenda")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("origem_venda");

                    b.Property<DateOnly?>("PrimeiraEntrega")
                        .HasColumnType("date")
                        .HasColumnName("primeira_entrega");

                    b.Property<string>("Rua")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("rua");

                    b.Property<string>("StatusFinanceiro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_financeiro");

                    b.Property<string>("Telefone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorRecorrenteMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_recorrente_mensal");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("FrequenciaEntregaId")
                        .HasDatabaseName("ix_clientes_frequencia");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_clientes_nome");

                    b.ToTable("clientes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_clientes_dia_cobranca", "dia_cobranca IS NULL OR (dia_cobranca BETWEEN 1 AND 31)");

                            t.HasCheckConstraint("ck_clientes_valor", "valor_recorrente_mensal >= 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Consumo.FaixaConsumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GramasPorDia")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_por_dia");

                    b.Property<decimal>("PesoFinal")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_final");

                    b.Property<decimal>("PesoInicial")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_inicial");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_faixas_consumo");

                    b.HasIndex("PesoInicial")
                        .HasDatabaseName("ix_faixas_consumo_peso_inicial");

                    b.ToTable("faixas_consumo", "public", t =>
                        {
                            t.HasCheckConstraint("ck_faixas_consumo_gramas", "gramas_por_dia > 0");

                            t.HasCheckConstraint("ck_faixas_consumo_peso", "peso_inicial < peso_final");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.Entrega", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("Bairro").HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("bairro");
                    b.Property<DateTimeOffset?>("CanceladaEm").HasColumnType("timestamp with time zone").HasColumnName("cancelada_em");
                    b.Property<string>("Cep").HasMaxLength(12).HasColumnType("character varying(12)").HasColumnName("cep");
                    b.Property<string>("Cidade").HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("cidade");
                    b.Property<long>("ClienteId").HasColumnType("bigint").HasColumnName("cliente_id");
                    b.Property<string>("ClienteNome").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)").HasColumnName("cliente_nome");
                    b.Property<string>("Complemento").HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("complemento");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateOnly>("DataPrevista").HasColumnType("date").HasColumnName("data_prevista");
                    b.Property<int>("DiasCiclo").HasColumnType("integer").HasColumnName("dias_ciclo");
                    b.Property<long?>("EntregadorId").HasColumnType("bigint").HasColumnName("entregador_id");
                    b.Property<string>("Estado").HasMaxLength(2).HasColumnType("character varying(2)").HasColumnName("estado");
                    b.Property<string>("FrequenciaNome").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)").HasColumnName("frequencia_nome");
                    b.Property<string>("MotivoCancelamento").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("motivo_cancelamento");
                    b.Property<string>("MotivoNaoEntrega").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("motivo_nao_entrega");
                    b.Property<string>("MotivoReagendamento").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("motivo_reagendamento");
                    b.Property<string>("Numero").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("numero");
                    b.Property<string>("ObservacoesEntregador").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("observacoes_entregador");
                    b.Property<string>("ObservacoesInternas").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("observacoes_internas");
                    b.Property<long?>("ReagendadaDeId").HasColumnType("bigint").HasColumnName("reagendada_de_id");
                    b.Property<DateTimeOffset?>("ReagendadaEm").HasColumnType("timestamp with time zone").HasColumnName("reagendada_em");
                    b.Property<long?>("ReagendadaParaId").HasColumnType("bigint").HasColumnName("reagendada_para_id");
                    b.Property<string>("Rua").HasMaxLength(160).HasColumnType("character varying(160)").HasColumnName("rua");
                    b.Property<string>("Status").IsRequired().HasMaxLength(25).HasColumnType("character varying(25)").HasColumnName("status");
                    b.Property<string>("Telefone").HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("telefone");
                    b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id").HasName("pk_entregas");
                    b.HasIndex("DataPrevista").HasDatabaseName("ix_entregas_data");
                    b.HasIndex("Status").HasDatabaseName("ix_entregas_status");
                    b.HasIndex("ClienteId", "DataPrevista").HasDatabaseName("ix_entregas_cliente_data");
                    b.ToTable("entregas", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaHistorico", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<long>("EntregaId").HasColumnType("bigint").HasColumnName("entrega_id");
                    b.Property<string>("Evento").IsRequired().HasMaxLength(400).HasColumnType("character varying(400)").HasColumnName("evento");
                    b.Property<DateTimeOffset>("Quando").HasColumnType("timestamp with time zone").HasColumnName("quando");
                    b.Property<string>("StatusDe").HasMaxLength(25).HasColumnType("character varying(25)").HasColumnName("status_de");
                    b.Property<string>("StatusPara").HasMaxLength(25).HasColumnType("character varying(25)").HasColumnName("status_para");
                    b.Property<string>("Usuario").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)").HasColumnName("usuario");
                    b.HasKey("Id").HasName("pk_entrega_historico");
                    b.HasIndex("EntregaId").HasDatabaseName("ix_entrega_historico_entrega");
                    b.ToTable("entrega_historico", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItem", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<long>("EntregaPetId").HasColumnType("bigint").HasColumnName("entrega_pet_id");
                    b.Property<int?>("QuantidadeCicloGramas").HasColumnType("integer").HasColumnName("quantidade_ciclo_gramas");
                    b.Property<int?>("QuantidadePacotes").HasColumnType("integer").HasColumnName("quantidade_pacotes");
                    b.Property<long>("ReceitaId").HasColumnType("bigint").HasColumnName("receita_id");
                    b.Property<string>("ReceitaCodigo").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("receita_codigo");
                    b.Property<string>("ReceitaNome").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("receita_nome");
                    b.Property<int?>("TamanhoPacoteGramas").HasColumnType("integer").HasColumnName("tamanho_pacote_gramas");
                    b.Property<string>("Tipo").IsRequired().HasMaxLength(15).HasColumnType("character varying(15)").HasColumnName("tipo");
                    b.HasKey("Id").HasName("pk_entrega_itens");
                    b.HasIndex("EntregaPetId").HasDatabaseName("ix_entrega_itens_pet");
                    b.HasIndex("ReceitaId").HasDatabaseName("ix_entrega_itens_receita");
                    b.ToTable("entrega_itens", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItemIngrediente", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("Categoria").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)").HasColumnName("categoria");
                    b.Property<decimal>("Coeficiente").HasPrecision(8, 4).HasColumnType("numeric(8,4)").HasColumnName("coeficiente");
                    b.Property<decimal>("CustoKgCru").HasPrecision(12, 2).HasColumnType("numeric(12,2)").HasColumnName("custo_kg_cru");
                    b.Property<long>("EntregaItemId").HasColumnType("bigint").HasColumnName("entrega_item_id");
                    b.Property<int>("GramasCozidas").HasColumnType("integer").HasColumnName("gramas_cozidas");
                    b.Property<long>("IngredienteId").HasColumnType("bigint").HasColumnName("ingrediente_id");
                    b.Property<string>("IngredienteNome").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)").HasColumnName("ingrediente_nome");
                    b.HasKey("Id").HasName("pk_entrega_item_ingredientes");
                    b.HasIndex("EntregaItemId").HasDatabaseName("ix_entrega_ingr_item");
                    b.HasIndex("IngredienteId").HasDatabaseName("ix_entrega_ingr_ingrediente");
                    b.ToTable("entrega_item_ingredientes", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItemPacote", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<long>("EntregaItemId").HasColumnType("bigint").HasColumnName("entrega_item_id");
                    b.Property<int>("PesoGramas").HasColumnType("integer").HasColumnName("peso_gramas");
                    b.Property<int>("Quantidade").HasColumnType("integer").HasColumnName("quantidade");
                    b.Property<string>("TamanhoLabel").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("tamanho_label");
                    b.HasKey("Id").HasName("pk_entrega_item_pacotes");
                    b.HasIndex("EntregaItemId").HasDatabaseName("ix_entrega_pacotes_item");
                    b.ToTable("entrega_item_pacotes", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaPet", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<long>("EntregaId").HasColumnType("bigint").HasColumnName("entrega_id");
                    b.Property<int?>("GramasDia").HasColumnType("integer").HasColumnName("gramas_dia");
                    b.Property<long>("PetId").HasColumnType("bigint").HasColumnName("pet_id");
                    b.Property<string>("PetNome").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)").HasColumnName("pet_nome");
                    b.Property<int>("QuantidadeTotalGramas").HasColumnType("integer").HasColumnName("quantidade_total_gramas");
                    b.Property<string>("TipoAlimentacao").IsRequired().HasMaxLength(15).HasColumnType("character varying(15)").HasColumnName("tipo_alimentacao");
                    b.HasKey("Id").HasName("pk_entrega_pets");
                    b.HasIndex("EntregaId").HasDatabaseName("ix_entrega_pets_entrega");
                    b.HasIndex("PetId").HasDatabaseName("ix_entrega_pets_pet");
                    b.ToTable("entrega_pets", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.FrequenciaEntrega", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DiasCiclo")
                        .HasColumnType("integer")
                        .HasColumnName("dias_ciclo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<bool>("Personalizada")
                        .HasColumnType("boolean")
                        .HasColumnName("personalizada");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_frequencias_entrega");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_frequencias_entrega_nome");

                    b.ToTable("frequencias_entrega", "public", t =>
                        {
                            t.HasCheckConstraint("ck_frequencias_entrega_dias", "personalizada = true OR (dias_ciclo IS NOT NULL AND dias_ciclo > 0)");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Papel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_papeis");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_papeis_nome");

                    b.ToTable("papeis", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("SistemaAN.Domain.Pacotes.TamanhoPacote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<int>("PesoGramas")
                        .HasColumnType("integer")
                        .HasColumnName("peso_gramas");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tamanhos_pacote");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_tamanhos_pacote_nome");

                    b.ToTable("tamanhos_pacote", "public", t =>
                        {
                            t.HasCheckConstraint("ck_tamanhos_pacote_peso", "peso_gramas > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Pets.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int?>("GramasDiaAjustadas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_dia_ajustadas");

                    b.Property<string>("IdadeAprox")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("idade_aprox");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacoesAlimentares")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_alimentares");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_gerais");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_kg");

                    b.Property<string>("Raca")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("raca");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sexo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pets_cliente_id");

                    b.ToTable("pets", "public", t =>
                        {
                            t.HasCheckConstraint("ck_pets_gramas_ajustadas", "gramas_dia_ajustadas IS NULL OR gramas_dia_ajustadas >= 0");

                            t.HasCheckConstraint("ck_pets_peso", "peso_kg > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoAlimentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GramasDiaAjustadas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_dia_ajustadas");

                    b.Property<int?>("GramasDiaSugeridas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas_dia_sugeridas");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint")
                        .HasColumnName("pet_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_planos_alimentares");

                    b.HasIndex("PetId")
                        .IsUnique()
                        .HasDatabaseName("ix_planos_alimentares_pet");

                    b.ToTable("planos_alimentares", "public", t =>
                        {
                            t.HasCheckConstraint("ck_planos_alimentares_gramas", "(gramas_dia_sugeridas IS NULL OR gramas_dia_sugeridas >= 0) AND (gramas_dia_ajustadas IS NULL OR gramas_dia_ajustadas >= 0)");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoItemPacote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PlanoItemReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_item_receita_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<long>("TamanhoPacoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_pacote_id");

                    b.HasKey("Id")
                        .HasName("pk_plano_item_pacotes");

                    b.HasIndex("PlanoItemReceitaId")
                        .HasDatabaseName("ix_plano_item_pacotes_item");

                    b.HasIndex("TamanhoPacoteId")
                        .HasDatabaseName("ix_plano_item_pacotes_tamanho");

                    b.ToTable("plano_item_pacotes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_plano_item_pacotes_qtd", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoItemReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PlanoAlimentarId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_alimentar_id");

                    b.Property<int?>("QuantidadeCicloGramas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_ciclo_gramas");

                    b.Property<int?>("QuantidadePacotes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_pacotes");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("receita_id");

                    b.HasKey("Id")
                        .HasName("pk_plano_itens_receita");

                    b.HasIndex("PlanoAlimentarId")
                        .HasDatabaseName("ix_plano_itens_receita_plano");

                    b.HasIndex("ReceitaId")
                        .HasDatabaseName("ix_plano_itens_receita_receita");

                    b.ToTable("plano_itens_receita", "public", t =>
                        {
                            t.HasCheckConstraint("ck_plano_itens_receita_ciclo", "quantidade_ciclo_gramas IS NULL OR quantidade_ciclo_gramas > 0");

                            t.HasCheckConstraint("ck_plano_itens_receita_pacotes", "quantidade_pacotes IS NULL OR quantidade_pacotes > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.ItemReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Gramas")
                        .HasColumnType("integer")
                        .HasColumnName("gramas");

                    b.Property<long>("IngredienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingrediente_id");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("receita_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_receita");

                    b.HasIndex("IngredienteId")
                        .HasDatabaseName("ix_itens_receita_ingrediente_id");

                    b.HasIndex("ReceitaId")
                        .HasDatabaseName("ix_itens_receita_receita_id");

                    b.ToTable("itens_receita", "public", t =>
                        {
                            t.HasCheckConstraint("ck_itens_receita_gramas", "gramas > 0");
                        });
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<long?>("PetId")
                        .HasColumnType("bigint")
                        .HasColumnName("pet_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_receitas");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_receitas_pet");

                    b.HasIndex("Tipo", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_receitas_tipo_codigo");

                    b.ToTable("receitas", "public");
                });

            modelBuilder.Entity("PapelUsuario", b =>
                {
                    b.HasOne("SistemaAN.Domain.Identity.Papel", null)
                        .WithMany()
                        .HasForeignKey("PapeisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_papeis_papeis_papeis_id");

                    b.HasOne("SistemaAN.Domain.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_papeis_usuarios_usuario_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Catalog.Ingrediente", b =>
                {
                    b.HasOne("SistemaAN.Domain.Catalog.CategoriaIngrediente", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredientes_categorias_ingredientes_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("SistemaAN.Domain.Identity.Usuario", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Pets.Pet", b =>
                {
                    b.HasOne("SistemaAN.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pets_clientes_cliente_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.ItemReceita", b =>
                {
                    b.HasOne("SistemaAN.Domain.Catalog.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_receita_ingredientes_ingrediente_id");

                    b.HasOne("SistemaAN.Domain.Receitas.Receita", null)
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_receita_receitas_receita_id");
                });

            modelBuilder.Entity("SistemaAN.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.FrequenciaEntrega", null)
                        .WithMany()
                        .HasForeignKey("FrequenciaEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_frequencia");
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoAlimentar", b =>
                {
                    b.HasOne("SistemaAN.Domain.Pets.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planos_alimentares_pet");
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoItemPacote", b =>
                {
                    b.HasOne("SistemaAN.Domain.Planos.PlanoItemReceita", null)
                        .WithMany("Pacotes")
                        .HasForeignKey("PlanoItemReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_item_pacotes_item");

                    b.HasOne("SistemaAN.Domain.Pacotes.TamanhoPacote", null)
                        .WithMany()
                        .HasForeignKey("TamanhoPacoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plano_item_pacotes_tamanho");
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoItemReceita", b =>
                {
                    b.HasOne("SistemaAN.Domain.Planos.PlanoAlimentar", null)
                        .WithMany("Itens")
                        .HasForeignKey("PlanoAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_itens_receita_plano");

                    b.HasOne("SistemaAN.Domain.Receitas.Receita", null)
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plano_itens_receita_receita");
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.Receita", b =>
                {
                    b.HasOne("SistemaAN.Domain.Pets.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_receitas_pet");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.Entrega", b =>
                {
                    b.HasOne("SistemaAN.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_cliente");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaHistorico", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.Entrega", null)
                        .WithMany("Historico")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_historico_entrega");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItem", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.EntregaPet", null)
                        .WithMany("Itens")
                        .HasForeignKey("EntregaPetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_itens_pet");

                    b.HasOne("SistemaAN.Domain.Receitas.Receita", null)
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_itens_receita");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItemIngrediente", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.EntregaItem", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("EntregaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_ingr_item");

                    b.HasOne("SistemaAN.Domain.Catalog.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_ingr_ingrediente");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItemPacote", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.EntregaItem", null)
                        .WithMany("Pacotes")
                        .HasForeignKey("EntregaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_pacotes_item");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaPet", b =>
                {
                    b.HasOne("SistemaAN.Domain.Entregas.Entrega", null)
                        .WithMany("Pets")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_pets_entrega");

                    b.HasOne("SistemaAN.Domain.Pets.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_pets_pet");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.Entrega", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaItem", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("SistemaAN.Domain.Entregas.EntregaPet", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaAN.Domain.Identity.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoAlimentar", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaAN.Domain.Planos.PlanoItemReceita", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("SistemaAN.Domain.Receitas.Receita", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
